### ISSUE TITLE
Incorrect tooltip position  on bottom(Wayland)

### ISSUE THREAD

**Issue by knm100** [lxqt/lxqt-panel#2092]
##### Expected Behavior

Display tooltip normally like KWIN_wayland
##### Current Behavior
Please see the video

https://github.com/user-attachments/assets/63cf9598-f53b-4c91-9207-994033f2ca41

##### Possible Solution

No idea
##### Steps to Reproduce (for bugs)

1. I think if you use  wlroots backend, you'll see this again.

##### System Information

* LXQt Version: 2.01
* Distribution & Version:Arch
* Qt Version:
* liblxqt Version:2.01
* lxqt-panel  Version: 2.0.1.r22.g246b33f1

**Comment by tsujan** [comment]
It's not our bug, but let's keep this open for a while.

**Comment by stefonarch** [comment]
Please add "on bottom or right panel" to your description.

**Comment by knm100** [comment]
> It's not our bug, but let's keep this open for a while.

It a bug of labwc?

**Comment by stefonarch** [comment]
It can be seen in all wlroots-based compositors and also in niri or cosmic (smithhay based). It's a Qt(-wayland) bug I guess. kwin has adopted a workaround probably.

**Comment by stefonarch** [comment]
More generally, the list of issues:
https://wiki.qt.io/QtWayland_Remaining_Issues

**Comment by knm100** [comment]
Thanks for the detailed explanation

**Comment by tsujan** [comment]
> kwin has adopted a workaround probably

If it's a workaround, it's only partial. This problem and that of some context menus may have the same root.

**Comment by knm100** [comment]
In QT 6.8, it looks like this bug has been fixed a little bit, at least the tooltips appear exactly where the icon is instead of far away from the icon

**Comment by stefonarch** [comment]
Yes, tooltip position follows now hovering over different items. But it's not fixed at bottom screen as it should be more above.

**Comment by tsujan** [comment]
Follow https://github.com/lxqt/lxqt-panel/issues/2171
